[package]
name = "backmarker"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
iced = {version = "0.13.1", features = ["tokio"]}
log = "0.4.25"

[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_Security",
    "Win32_System_Memory"
]
