[package]
name = "backmarker"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.13.1", features = ["tokio"]}

[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_Security",
    "Win32_System_Memory"
]
